services:
  backend:
    build: ./backend
    container_name: onfly_api
    env_file: ./backend/.env
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8081:8000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onfly
      MYSQL_USER: onfly
      MYSQL_PASSWORD: onfly
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build: 
      context: ./frontend
      args:
        SUBFOLDER: /front/
    container_name: onfly_front
    volumes:
      - ./frontend:/app
    ports:
      - "9000:80"
    depends_on:
      - backend

volumes:
  db_data:
